# -*- coding: utf-8 -*-
"""rfm_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18WZl3D22uvaHEZeQWURBzbyTYAuNKbRR
"""

import pandas as pd
import datetime as dt
import plotly.express as px
import plotly.graph_objects as go
import plotly.colors

import kagglehub
path = kagglehub.dataset_download("ulrikthygepedersen/online-retail-dataset")

df = pd.read_csv(f"{path}/online_retail.csv")

df.head()

df.info()

df.shape

df.dropna(subset = ['CustomerID'], inplace = True)

df.InvoiceDate = pd.to_datetime(df.InvoiceDate)
df['TotalAmount'] = df['Quantity'] * df['UnitPrice']

df.head()

reference_date = pd.Timestamp(dt.datetime.now().date())

reference_date = df['InvoiceDate'].max() + dt.timedelta(days=1)

reference_date

rfm = df.groupby('CustomerID').agg(
    Recency=('InvoiceDate', lambda x: (reference_date - x.max()).days),
    Frequency=('InvoiceDate', 'count'),
    Value=('TotalAmount', 'sum')
)

# The columns are already named 'Recency', 'Frequency', 'Value' in the previous step,
# so renaming is not needed.
# rfm.rename(columns={'InvoiceDate': 'Frequency', 'TotalAmount': 'Value'}, inplace=True)
rfm.head()

# Define quantiles
quantiles = rfm.quantile(q=[0.25, 0.5, 0.75])

# Assign RFM scores
def RScore(x, p, d):
    if p == 'Recency':
        if x <= d[p][0.25]:
            return 4
        elif x <= d[p][0.50]:
            return 3
        elif x <= d[p][0.75]:
            return 2
        else:
            return 1
    else:
        if x <= d[p][0.25]:
            return 1
        elif x <= d[p][0.50]:
            return 2
        elif x <= d[p][0.75]:
            return 3
        else:
            return 4
rfm['R'] = rfm['Recency'].apply(RScore, args=('Recency', quantiles))
rfm['F'] = rfm['Frequency'].apply(RScore, args=('Frequency', quantiles))
rfm['M'] = rfm['Value'].apply(RScore, args=('Value', quantiles))
rfm.head()

rfm['RFM_Segment'] = rfm['R'].astype(str) + rfm['F'].astype(str) + rfm['M'].astype(str)
rfm['RFM_Score'] = rfm[['R', 'F', 'M']].sum(axis=1)

rfm.head()

segment_labels = ['low value', 'mid value', 'high value']
rfm['Value_Segment'] = pd.qcut(rfm['Value'], q=3, labels=segment_labels)

rfm.head()

segment_labels = ['Low-Value', 'Mid-Value', 'High-Value']

def assign_segment(score):
    if score < 5:
        return 'Low-Value'
    elif score < 9:
        return 'Mid-Value'
    else:
        return 'High-Value'

rfm['RFM_Segment_Label'] = rfm['RFM_Score'].apply(assign_segment)

rfm.head()

segment_counts = rfm['RFM_Segment_Label'].value_counts().reset_index()
segment_counts.columns = ['RFM_Segment', 'Count']
segment_counts = segment_counts.sort_values('RFM_Segment')

# Create the bar chart using Plotly
fig = px.bar(
    segment_counts,
    x='RFM_Segment',
    y='Count',
    title='Customer Distribution by RFM Segment',
    labels={'RFM_Segment': 'RFM Segment', 'Count': 'Number of Customers'},
    color='RFM_Segment',
    color_discrete_sequence=px.colors.qualitative.Pastel
)

fig.show()

rfm['RFM_Customer_Segments'] = ''

rfm.loc[rfm['RFM_Score'] >= 9, 'RFM_Customer_Segments'] = 'VIP/Loyal'
rfm.loc[(rfm['RFM_Score'] >= 6) & (rfm['RFM_Score'] < 9), 'RFM_Customer_Segments'] = 'Potential Loyal'
rfm.loc[(rfm['RFM_Score'] >= 5) & (rfm['RFM_Score'] < 6), 'RFM_Customer_Segments'] = 'At Risk Customers'
rfm.loc[(rfm['RFM_Score'] >= 4) & (rfm['RFM_Score'] < 5), 'RFM_Customer_Segments'] = "Can't Lose"
rfm.loc[(rfm['RFM_Score'] >= 3) & (rfm['RFM_Score'] < 4), 'RFM_Customer_Segments'] = 'Lost'

segment_counts = rfm['RFM_Customer_Segments'].value_counts().sort_index()

segment_product_counts = rfm.groupby(
    ['RFM_Segment_Label', 'RFM_Customer_Segments']
).size().reset_index(name='Count')

segment_product_counts = segment_product_counts.sort_values('Count', ascending=False)

# Create the treemap
fig_treemap_segment_product = px.treemap(
    segment_product_counts,
    path=['RFM_Segment_Label', 'RFM_Customer_Segments'],
    values='Count',
    color='RFM_Segment_Label',
    color_discrete_sequence=px.colors.qualitative.Pastel,
    title='RFM Customer Segments by Value'
)

# Display the treemap
fig_treemap_segment_product.show()

vip_segment = rfm[rfm['RFM_Customer_Segments'] == 'VIP/Loyal']

fig = go.Figure()
fig.add_trace(go.Box(y=vip_segment['Recency'], name='Recency'))
fig.add_trace(go.Box(y=vip_segment['Frequency'], name='Frequency'))
fig.add_trace(go.Box(y=vip_segment['Value'], name='Value'))

fig.show()

correlation_matrix = vip_segment[['R', 'F', 'M']].corr()

fig_heatmap = go.Figure(data=go.Heatmap(
    z=correlation_matrix.values,
    x=correlation_matrix.columns,
    y=correlation_matrix.columns,
    colorscale='RdBu',
    colorbar=dict(title='Correlation')
))

fig_heatmap.update_layout(title='Correlation Matrix of RFM Values within Champions Segment')

# Display the heatmap
fig_heatmap.show()

pastel_colors = plotly.colors.qualitative.Pastel

fig = go.Figure(data=[go.Bar(
    x=segment_counts.index,
    y=segment_counts.values,
    marker=dict(color=pastel_colors)
)])

vip_color = 'rgb(158, 202, 225)'

fig.update_traces(
    marker_color=[vip_color if segment == 'Champions' else pastel_colors[i]
                  for i, segment in enumerate(segment_counts.index)],
    marker_line_color='rgb(8, 48, 107)',
    marker_line_width=1.5,
    opacity=0.6
)

# Update the layout
fig.update_layout(
    title='Comparison of RFM Segments',
    xaxis_title='RFM Segments',
    yaxis_title='Number of Customers',
    showlegend=False
)

# Display the figure
fig.show()

segment_scores = rfm.groupby('RFM_Customer_Segments')[['R', 'F', 'M']].mean().reset_index()
fig = go.Figure()

# Add bars for Recency score
fig.add_trace(go.Bar(
    x=segment_scores['RFM_Customer_Segments'],
    y=segment_scores['R'],
    name='Recency Score',
    marker_color='rgb(158,202,225)'
))

# Add bars for Frequency score
fig.add_trace(go.Bar(
    x=segment_scores['RFM_Customer_Segments'],
    y=segment_scores['F'],
    name='Frequency Score',
    marker_color='rgb(94,158,217)'
))

# Add bars for Monetary score
fig.add_trace(go.Bar(
    x=segment_scores['RFM_Customer_Segments'],
    y=segment_scores['M'],
    name='Monetary Score',
    marker_color='rgb(32,102,148)'
))

# Update the layout
fig.update_layout(
    title='Comparison of RFM Segments based on Recency, Frequency, and Monetary Scores',
    xaxis_title='RFM Segments',
    yaxis_title='Score',
    barmode='group'
)

fig.show()

